import {
  Assignment,
  Course,
  StringNumberLookup,
  StringStringLookup,
} from '../types';
import { getWeekStart } from '../utils/getWeek';

/*
  Pretty demo assignments
*/

const days = [];
for (let i = 1; i < 7; i++) {
  const day = getWeekStart(1);
  day.setDate(day.getDate() + i);
  day.setHours(8, 30, 0);
  days.push(day.toISOString());
}

const DemoAssignments: Assignment[] = [
  {
    color: '#8F3E97',
    html_url: '#',
    name: 'Worksheet 6.4',
    points_possible: 10,
    due_at: days[0],
    course_id: 1,
    id: 10,
    user_submitted: false,
    is_quiz_assignment: false,
    course_name: 'Algebra 2 - Smith',
    grade: 0,
  },
  {
    color: '#8F3E97',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[0],
    course_id: 1,
    id: 10,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Algebra 2 - Smith',
    grade: 0,
  },
  {
    color: '#1770AB',
    html_url: '#',
    name: 'Socratic Seminar',
    points_possible: 20,
    due_at: days[1],
    course_id: 2,
    id: 11,
    user_submitted: false,
    is_quiz_assignment: false,
    course_name: 'English 11 - Brown',
    grade: 0,
    discussion_topic: 0,
  },
  {
    color: '#1770AB',
    html_url: '#',
    name: 'Macbeth Essay',
    points_possible: 50,
    due_at: days[4],
    course_id: 2,
    id: 14,
    user_submitted: false,
    is_quiz_assignment: false,
    course_name: 'English 11 - Brown',
    grade: 0,
    discussion_topic: 0,
  },
  {
    color: '#1770AB',
    html_url: '#',
    name: 'Sonnet #26 Response',
    points_possible: 15,
    due_at: days[5],
    course_id: 2,
    id: 15,
    user_submitted: false,
    is_quiz_assignment: false,
    course_name: 'English 11 - Brown',
    grade: 0,
    discussion_topic: 0,
  },
  {
    color: '#1770AB',
    html_url: '#',
    name: 'Done',
    points_possible: 15,
    due_at: days[2],
    course_id: 2,
    id: 21,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'English 11 - Brown',
    grade: 0,
    discussion_topic: 0,
  },
  {
    color: '#1770AB',
    html_url: '#',
    name: 'Done',
    points_possible: 15,
    due_at: days[2],
    course_id: 2,
    id: 22,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'English 11 - Brown',
    grade: 0,
    discussion_topic: 0,
  },
  {
    color: '#FF2717',
    html_url: '#',
    name: 'Done',
    points_possible: 15,
    due_at: days[2],
    course_id: 3,
    id: 41,
    user_submitted: true,
    is_quiz_assignment: true,
    course_name: 'US History - Jones',
    grade: 0,
  },
  {
    color: '#FF2717',
    html_url: '#',
    name: 'Done',
    points_possible: 15,
    due_at: days[2],
    course_id: 3,
    id: 42,
    user_submitted: true,
    is_quiz_assignment: true,
    course_name: 'US History - Jones',
    grade: 0,
  },
  {
    color: '#FF2717',
    html_url: '#',
    name: 'Done',
    points_possible: 15,
    due_at: days[2],
    course_id: 3,
    id: 43,
    user_submitted: true,
    is_quiz_assignment: true,
    course_name: 'US History - Jones',
    grade: 0,
  },
  {
    color: '#FF2717',
    html_url: '#',
    name: 'Monroe Doctrine Quiz',
    points_possible: 15,
    due_at: days[2],
    course_id: 3,
    id: 12,
    user_submitted: false,
    is_quiz_assignment: true,
    course_name: 'US History - Jones',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Nitrogen Cycle Worksheet',
    points_possible: 10,
    due_at: days[3],
    course_id: 4,
    id: 13,
    user_submitted: false,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[2],
    course_id: 4,
    id: 41,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[2],
    course_id: 4,
    id: 42,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[2],
    course_id: 4,
    id: 43,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[2],
    course_id: 4,
    id: 44,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
  {
    color: '#009606',
    html_url: '#',
    name: 'Done',
    points_possible: 10,
    due_at: days[2],
    course_id: 4,
    id: 45,
    user_submitted: true,
    is_quiz_assignment: false,
    course_name: 'Biology - McCoy',
    grade: 0,
  },
];

const DemoCourses: Course[] = [
  {
    id: 1,
    color: '#8F3E97',
    name: 'Algebra 2 - Smith',
    position: 0,
  },
  {
    id: 2,
    color: '#1770AB',
    name: 'English 11 - Brown',
    position: 1,
  },
  {
    id: 3,
    color: '#FF2717',
    name: 'US History - Jones',
    position: 2,
  },
  {
    id: 4,
    color: '#009606',
    name: 'Biology - McCoy',
    position: 3,
  },
];

const DemoPositions: StringNumberLookup = {
  1: 3,
  2: 2,
  3: 1,
  4: 0,
};

const DemoColors: StringStringLookup = {
  1: '#8F3E97',
  2: '#1770AB',
  3: '#FF2717',
  4: '#009606',
};

const DemoNames: StringStringLookup = {
  1: 'Algebra 2 - Smith',
  2: 'English 11 - Brown',
  3: 'US History - Jones',
  4: 'Biology - McCoy',
};

export { DemoAssignments, DemoCourses, DemoColors, DemoNames, DemoPositions };
